# Generated by Django 5.0.6 on 2024-06-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='images/d.jpg', null=True, upload_to='images'),
        ),
    ]
